[package]
name = "declutter"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["color", "help", "usage", "error-context", "suggestions", "derive"] }
url = { version = "2.5.0", features = [] }
